### ISSUE TITLE
Website Monitor Create error

### ISSUE THREAD

**Issue by crisp2u** [Bonial-International-GmbH/terraform-provider-site24x7#19]
Hello, I started playing a bit with this provider and tried to use the websitemonitor resource. After creation I'm getting the following error:
```
Error: json: cannot unmarshal string into Go struct field ValueAndSeverity.matching_keyword.severity of type api.Status
```

The resource is created but i think when read it fails.  The relevant attributes I used are: 

```hcl
  // (Optional) Check for the keyword in the website response.
  matching_keyword_value = "Some text"

  // (Optional) Alert type to match on. See
  // https://www.site24x7.com/help/api/#alert-type-constants for available
  // values.
  matching_keyword_severity = 0

  // (Optional) Check for non existence of keyword in the website response.
  unmatching_keyword_value = "error,SQLException"

  // (Optional) Alert type to match on. See
  // https://www.site24x7.com/help/api/#alert-type-constants for available
  // values.
  unmatching_keyword_severity = 2

```

Any ideea what's wrong ?

**Comment by martinohmann** [comment]
@crisp2u Thanks for reporting the issue. PR #20 bumps the site24x7-go API client version and should fix the issue. I created a new tagged release which includes the fix: https://github.com/Bonial-International-GmbH/terraform-provider-site24x7/releases/tag/v0.0.3
