### ISSUE TITLE
add import documentation

### ISSUE THREAD

**Issue by xsnrg** [Bonial-International-GmbH/terraform-provider-site24x7#30]
https://registry.terraform.io/providers/Bonial-International-GmbH/site24x7/latest/docs

I see a pull request was merged about a year ago to add web monitor importing, but there is no documentation on the above page about any importing abilities.

**Comment by martinohmann** [comment]
Hi @xsnrg.

Thanks for raising this. I just updated the docs and pushed a new release so it's now reflected here: https://registry.terraform.io/providers/Bonial-International-GmbH/site24x7/latest/docs/resources/website_monitor
