### ISSUE TITLE
existing website_monitors are modified when adding new monitors

### ISSUE THREAD

**Issue by xsnrg** [Bonial-International-GmbH/terraform-provider-site24x7#32]
I use a list variable in terraform like this:

```
monitors = [
"monitor1.domain.com" = "https://monitor1.domain.com"
"monitor2.domain.com" = "https://monitor2.domain.com"
]
```
and then in a module:
```
count = length(var.monitors)
display_name = keys(var.monitors)[count.index]
website = values(var.monitors)[count.index]
```
This works until a new monitor is added to the monitors list. If the  display_name is alphabetically before `monitor1.domain.com`, such as `a.domain.com`, then the new monitor is added by updating the first existing monitor ID instead of creating a new monitor.  This throws off all of the associated alerting and history for all monitors in the list! The last monitor in the list alphabetically, is created as a new monitor without any history. In `terraform plan` this can be seen by the elements being updated on the previously existing ID.

If the new monitor is alphabetically after `monitor2.domain.com`, such as `z.domain.com`, then the new monitor is created as a new monitor with its own unique ID.

The existing monitors should not change when adding a new monitor so that history, groupings, alertings, etc are preserved. A new monitor should always be created with a new ID at site24x7.

This is a serious problem for any organizations that change monitors after the first apply.

**Comment by martinohmann** [comment]
Hello @xsnrg, the problem you describe is not specific to this provider but a limitation of terraform itself. You may want to switch from `count` to `for_each` which better suited for your use case. This will not cause recreations of all subsequent items in a list if you add or remove something in the middle.

https://www.terraform.io/docs/language/meta-arguments/for_each.html

**Comment by xsnrg** [comment]
Thank you, I will try the for_each approach.

**Comment by martinohmann** [comment]
I'm going to close this issue as it's not specific to this project.
